version: '3'
services:
  nodejs:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vulnapk
    command: --default-authentication-plugin=mysql_native_password

    volumes:
      - ./vulnapk.sql:/docker-entrypoint-initdb.d/vulnapk.sql
